suppressPackageStartupMessages({
  library(Seurat); library(SeuratDisk); library(SoupX)
  library(scDblFinder); library(SingleCellExperiment)
  library(Matrix); library(data.table); library(dplyr)
  library(ggplot2); library(patchwork); library(future)
  library(readr); library(yaml)
})
set.seed(42); plan("sequential")
options(future.globals.maxSize = 20 * 1024^3, future.seed = TRUE)
params <- yaml::read_yaml("config/params.yml")
read_10x <- function(outs_path) Read10X(data.dir = file.path(outs_path, "filtered_feature_bc_matrix"))
if (!dir.exists("figures")) dir.create("figures", recursive = TRUE)
if (!dir.exists("data/processed")) dir.create("data/processed", recursive = TRUE)
source("utils/plotting.R")
writeLines(capture.output(sessionInfo()), "data/processed/sessionInfo_00.txt")
