source("scripts/00_setup.R")
suppressPackageStartupMessages({ library(CellChat); library(NMF); library(ggalluvial) })
obj <- readRDS("data/processed/06_neurons.rds")
data.input <- GetAssayData(obj, assay="RNA", slot="data")
meta <- data.frame(labels=obj$seurat_clusters, row.names=colnames(obj))
meta$labels <- factor(paste0("cluster_", meta$labels), levels=paste0("cluster_", sort(unique(obj$seurat_clusters))))
cellchat <- createCellChat(object=data.input, meta=meta, group.by="labels")
data(CellChatDB.mouse); CellChatDB.use <- subsetDB(CellChatDB.mouse, search="Secreted Signaling")
cellchat@DB <- CellChatDB.use
cellchat <- subsetData(cellchat)
cellchat <- identifyOverExpressedGenes(cellchat, thresh.pc=0.2)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- computeCommunProb(cellchat)
cellchat <- filterCommunication(cellchat, min.cells=10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name="netP")
p <- netAnalysis_signalingRole_scatter(cellchat, dot.size=c(2,6), label.size=4, dot.alpha=0.4)
write_plot(p, "07_cellchat_scatter", pdf=TRUE)
pdf("figures/07_cellchat_role-heatmaps.pdf", width=10, height=8)
netAnalysis_signalingRole_heatmap(cellchat, pattern="outgoing", height=11)
netAnalysis_signalingRole_heatmap(cellchat, pattern="incoming", height=11)
dev.off()
pdf("figures/07_cellchat_outgoing_river-dot.pdf", width=10, height=8)
netAnalysis_river(cellchat, pattern="outgoing")
netAnalysis_dot(cellchat, pattern="outgoing")
dev.off()
pdf("figures/07_cellchat_incoming_river-dot.pdf", width=10, height=8)
netAnalysis_river(cellchat, pattern="incoming")
netAnalysis_dot(cellchat, pattern="incoming")
dev.off()
saveRDS(cellchat, "data/processed/07_cellchat_object.rds")
writeLines(capture.output(sessionInfo()), "data/processed/sessionInfo_07.txt")
